import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialBaseline1784561601801 implements MigrationInterface {
    name = 'InitialBaseline1784561601801'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar(64) NOT NULL, "password" varchar(256) NOT NULL, "role" varchar(16) NOT NULL DEFAULT ('viewer'), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "uat_records" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "item_name" varchar(128) NOT NULL, "category" varchar(32) NOT NULL, "test_step" text, "expected_result" text, "actual_result" text, "status" varchar(32) NOT NULL DEFAULT ('pending'), "tester" varchar(64), "remark" text, "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a9dfa2b01ea47f870d816a40a1" ON "uat_records" ("item_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c22473aebe935929206fa0859" ON "uat_records" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_f5aec40c90481934f34812a27b" ON "uat_records" ("status") `);
        await queryRunner.query(`CREATE TABLE "test_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "test_type" varchar(32) NOT NULL, "target_type" varchar(32) NOT NULL, "target_id" varchar(128) NOT NULL, "command" varchar(64), "params" text, "result" text, "success" boolean NOT NULL DEFAULT (0), "duration_ms" integer NOT NULL DEFAULT (0), "operator" varchar(64) NOT NULL DEFAULT ('tester'), "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_8421ec201cd5faa739bea5ae69" ON "test_logs" ("test_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d6364e37ab492de1890459ce9" ON "test_logs" ("target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8aa4cd9b5b3df766131a6cf6f1" ON "test_logs" ("target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e17e3fceab179e221cfbf12702" ON "test_logs" ("success") `);
        await queryRunner.query(`CREATE INDEX "IDX_47f725cebdba28aa831919e35b" ON "test_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "scheduler_tasks" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(128) NOT NULL, "code" varchar(64), "description" text, "cron" varchar(64) NOT NULL, "scene_code" varchar(64) NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "last_run_at" datetime, "next_run_at" datetime, "last_run_status" varchar(32), "last_run_message" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7fb5dafd650ee26023627ce351" ON "scheduler_tasks" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_1dae30dc36edfd45fbe40a3ff8" ON "scheduler_tasks" ("code") `);
        await queryRunner.query(`CREATE TABLE "system_branding_v2" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "systemName" varchar(80) NOT NULL, "systemSubtitle" varchar(60), "logoText" varchar(4) NOT NULL DEFAULT ('金'), "logoUrl" varchar, "browserTitle" varchar(80), "copyright" varchar(120), "welcome_media_id" integer, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "scene_actions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scene_id" integer NOT NULL, "device_type" varchar(32) NOT NULL, "device_id" varchar(128) NOT NULL, "command" varchar(64) NOT NULL, "params" text NOT NULL DEFAULT ('{}'), "delay_ms" integer NOT NULL DEFAULT (0), "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_046439be52ebc0d499e7e16ca5" ON "scene_actions" ("scene_id") `);
        await queryRunner.query(`CREATE TABLE "scenes" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "description" text, "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f376f84e976d24c79aadbf4b58" ON "scenes" ("code") `);
        await queryRunner.query(`CREATE TABLE "scene_executions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "execution_id" varchar(64) NOT NULL, "scene_code" varchar(64) NOT NULL, "scene_name" varchar(128) NOT NULL, "trigger_type" varchar(16) NOT NULL, "trigger_source" varchar(128) NOT NULL, "status" varchar(32) NOT NULL DEFAULT ('pending'), "started_at" datetime, "finished_at" datetime, "duration_ms" integer NOT NULL DEFAULT (0), "total_actions" integer NOT NULL DEFAULT (0), "success_count" integer NOT NULL DEFAULT (0), "failed_count" integer NOT NULL DEFAULT (0), "result_summary" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d034c032080709f018caf9e0f3" ON "scene_executions" ("execution_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_796db607efd396a74b80a9c931" ON "scene_executions" ("scene_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_dfd7d6c80251c65d25d66a0103" ON "scene_executions" ("trigger_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_096dc7077ab41db07ff421f849" ON "scene_executions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b10a37bb435779760fd8d65c85" ON "scene_executions" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "power_circuit" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "floor" varchar(16) NOT NULL, "category" varchar(32) NOT NULL DEFAULT ('misc'), "gateway_code" varchar(64), "relay_channel" integer, "meter_address" integer, "rated_voltage" integer NOT NULL DEFAULT (220), "rated_current" integer NOT NULL DEFAULT (16), "rated_power" integer NOT NULL DEFAULT (0), "sort_order" integer NOT NULL DEFAULT (100), "icon" varchar(32), "description" text, "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d0389afb4f67214ffd193d4a8a" ON "power_circuit" ("code") `);
        await queryRunner.query(`CREATE TABLE "playlist_item" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slot" integer NOT NULL, "media_id" integer NOT NULL, "title" varchar(120), "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "uq_playlist_slot_media" UNIQUE ("slot", "media_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bd653b06977753eb94f5ee893" ON "playlist_item" ("slot") `);
        await queryRunner.query(`CREATE TABLE "playback_history" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slot" integer NOT NULL, "media_id" integer NOT NULL, "media_name" varchar(200) NOT NULL, "played_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_83aea8276a638b5680b2256b41" ON "playback_history" ("slot") `);
        await queryRunner.query(`CREATE TABLE "playback_channels" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slot" integer NOT NULL, "name" varchar(80) NOT NULL, "outputKind" varchar(32) NOT NULL, "currentMediaId" integer, "currentPlaylistId" integer, "playlistIndex" integer NOT NULL DEFAULT (0), "startedAt" datetime, "loopMode" varchar(16) NOT NULL DEFAULT ('once'), "playMode" varchar(16) NOT NULL DEFAULT ('loopAll'), "paused" boolean NOT NULL DEFAULT (0), "lastHeartbeatAt" datetime, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7c5faf5c86c501f67d8533d0b1" ON "playback_channels" ("slot") `);
        await queryRunner.query(`CREATE TABLE "operation_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "operator" varchar(64) NOT NULL DEFAULT ('system'), "terminal" varchar(64), "action" varchar(64) NOT NULL, "target_type" varchar(32) NOT NULL, "target_id" varchar(64), "result" varchar(16) NOT NULL DEFAULT ('success'), "message" text, "duration_ms" integer NOT NULL DEFAULT (0), "retry_count" integer NOT NULL DEFAULT (1), "timeout_ms" integer, "raw_response" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1fd6d1b5856cc0958b2add833" ON "operation_logs" ("operator") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6e545189a34b54117d9fc7f0e" ON "operation_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_05aa79d806bd30b09b756dce93" ON "operation_logs" ("target_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b5947763b1f5e3e33942ab5b7" ON "operation_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "media_assets" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "originalName" varchar(255) NOT NULL, "safeName" varchar(255) NOT NULL, "path" varchar(500) NOT NULL, "thumbPath" varchar(500), "kind" varchar(16) NOT NULL, "sourceUrl" varchar(1000), "mimeType" varchar(128) NOT NULL, "sizeBytes" bigint NOT NULL, "durationSec" integer, "resolution" varchar(32), "remark" varchar(500), "uploader" varchar(64) NOT NULL DEFAULT ('system'), "last_played_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b5020667b8938c708210d09a6" ON "media_assets" ("kind") `);
        await queryRunner.query(`CREATE TABLE "light_zone" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "floor" varchar(16) NOT NULL, "gateway_code" varchar(64), "dali_group" integer, "sort_order" integer NOT NULL DEFAULT (100), "icon" varchar(32), "description" text, "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3dec5d43d95019fa40b4c0f615" ON "light_zone" ("code") `);
        await queryRunner.query(`CREATE TABLE "light_group" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "gateway_code" varchar(64) NOT NULL, "dali_group" integer NOT NULL, "zone_code" varchar(64), "shorts" text, "sort_order" integer NOT NULL DEFAULT (100), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "uq_light_group_gw_group" UNIQUE ("gateway_code", "dali_group"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0890fb46621b4af51ca658c591" ON "light_group" ("gateway_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9f27da6e6305bfcf52c859807" ON "light_group" ("zone_code") `);
        await queryRunner.query(`CREATE TABLE "hvac_zone" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "floor" varchar(16) NOT NULL, "indoors" text NOT NULL, "sort_order" integer NOT NULL DEFAULT (100), "description" text, "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_57a6442697b26d72122d1602c2" ON "hvac_zone" ("code") `);
        await queryRunner.query(`CREATE TABLE "hvac_indoor" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "idx" integer NOT NULL, "name" varchar(64) NOT NULL, "floor" varchar(16) NOT NULL, "zone_code" varchar(64), "model" varchar(64), "sort_order" integer NOT NULL DEFAULT (100), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d818582834958bb3838ea32be5" ON "hvac_indoor" ("idx") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f4da5a85603142e0b7e34b6c0" ON "hvac_indoor" ("zone_code") `);
        await queryRunner.query(`CREATE TABLE "hardware_units" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(64) NOT NULL, "name" varchar(128) NOT NULL, "category" varchar(32) NOT NULL, "vendor" varchar(64) NOT NULL, "model" varchar(64) NOT NULL, "driverKind" varchar(64), "serialNo" varchar(128), "firmwareVersion" varchar(64), "location" varchar(128), "floor" varchar(16), "ip" varchar(64), "macAddress" varchar(32), "addressing" text, "channels" text, "status" varchar(16) NOT NULL DEFAULT ('normal'), "enabled" boolean NOT NULL DEFAULT (1), "remark" text, "installedAt" varchar(32), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fbb2a88e4560cf92580a40614b" ON "hardware_units" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_85258d496323a08d27df01816f" ON "hardware_units" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_647fdcd283a2d28954f35e8159" ON "hardware_units" ("driverKind") `);
        await queryRunner.query(`CREATE TABLE "driver_templates" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "kind" varchar(64) NOT NULL, "displayName" varchar(128) NOT NULL, "vendor" varchar(64) NOT NULL, "category" varchar(32) NOT NULL, "protocol" varchar(64) NOT NULL, "capabilitiesJson" text NOT NULL, "defaultAddressingJson" text, "paramSchemaJson" text, "remark" text, "builtin" boolean NOT NULL DEFAULT (1), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6bc70405ac48a8c43c7d4f953e" ON "driver_templates" ("kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_16f484a7424fc3685085c8a688" ON "driver_templates" ("category") `);
        await queryRunner.query(`CREATE TABLE "devices" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(128) NOT NULL, "category" varchar(32) NOT NULL, "protocol" varchar(64) NOT NULL DEFAULT ('tcp'), "adapter" varchar(64) NOT NULL DEFAULT ('mock'), "ip" varchar(64), "address" varchar(128), "floor" varchar(32), "zone" varchar(64), "enabled" boolean NOT NULL DEFAULT (1), "status" varchar(32) NOT NULL DEFAULT ('offline'), "debug_remark" text, "last_test_at" datetime, "last_test_result" varchar(256), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_25a895dfc7796eab1da289796f" ON "devices" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f102b281aa9b07d72ca5197ed" ON "devices" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_c37da3607f7214c3dda1803d09" ON "devices" ("status") `);
        await queryRunner.query(`CREATE TABLE "client_auth_v1" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "passwordHash" varchar(255) NOT NULL, "passwordChangedAt" datetime NOT NULL, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(128) NOT NULL, "displayName" varchar(128), "logoUrl" varchar(512), "country" varchar(64), "website" varchar(256), "salesContact" varchar(256), "techContact" varchar(256), "remark" text, "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_96db6bbbaa6f23cad26871339b" ON "brands" ("name") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "entityType" varchar(32) NOT NULL, "entityId" varchar(64) NOT NULL, "action" varchar(16) NOT NULL, "operator" varchar(64) NOT NULL DEFAULT ('admin'), "snapshotBefore" text, "snapshotAfter" text, "remark" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_01993ae76b293d3b866cc3a125" ON "audit_logs" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f23279fad63453147a8efb46cf" ON "audit_logs" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "audio_scene" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preset_num" integer NOT NULL, "name" varchar(64) NOT NULL, "hint" varchar(128), "content" text, "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de2c659baf331df3651dad07e5" ON "audio_scene" ("preset_num") `);
        await queryRunner.query(`CREATE TABLE "audio_output_zone" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "channel" integer NOT NULL, "name" varchar(64) NOT NULL, "floor" varchar(16), "color" varchar(16), "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b76f6076f7da68d767258ac71b" ON "audio_output_zone" ("channel") `);
        await queryRunner.query(`CREATE TABLE "audio_input_source" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "channel" integer NOT NULL, "name" varchar(64) NOT NULL, "color" varchar(16), "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "desired_gain_db" float, "desired_muted" boolean, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aabbc290e3165fe043d1ad565d" ON "audio_input_source" ("channel") `);
        await queryRunner.query(`CREATE TABLE "audio_desired_link" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "out_ch" integer NOT NULL, "in_ch" integer NOT NULL, "enabled" boolean NOT NULL DEFAULT (0), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "uq_audio_desired_link" UNIQUE ("out_ch", "in_ch"))`);
        await queryRunner.query(`CREATE TABLE "app_release_v1" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "platform" varchar(16) NOT NULL, "versionCode" integer NOT NULL, "versionName" varchar(32) NOT NULL, "download_url" varchar(512) NOT NULL, "notes" text, "force_update" boolean NOT NULL DEFAULT (0), "min_supported_version_code" integer NOT NULL DEFAULT (1), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a54ecddcea1bb90f7cf90ccb1f" ON "app_release_v1" ("platform") `);
        await queryRunner.query(`CREATE TABLE "alerts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "level" varchar(16) NOT NULL, "type" varchar(64) NOT NULL, "source_type" varchar(32) NOT NULL, "source_id" varchar(128), "title" varchar(256) NOT NULL, "message" text, "status" varchar(16) NOT NULL DEFAULT ('active'), "resolved_at" datetime, "resolved_by" varchar(64), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ad88d0fa69fb016405bc8ddd8" ON "alerts" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5262085cf88e336618af2cc68" ON "alerts" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_da59bc445b71f4e501ce8bb05b" ON "alerts" ("source_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_b63189bf8e5abf5b9188acca96" ON "alerts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a56f667c22a7afc04b8a45f83" ON "alerts" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "admin_auth_v1" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "passwordHash" varchar(255) NOT NULL, "passwordChangedAt" datetime NOT NULL, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`DROP INDEX "IDX_046439be52ebc0d499e7e16ca5"`);
        await queryRunner.query(`CREATE TABLE "temporary_scene_actions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scene_id" integer NOT NULL, "device_type" varchar(32) NOT NULL, "device_id" varchar(128) NOT NULL, "command" varchar(64) NOT NULL, "params" text NOT NULL DEFAULT ('{}'), "delay_ms" integer NOT NULL DEFAULT (0), "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_046439be52ebc0d499e7e16ca53" FOREIGN KEY ("scene_id") REFERENCES "scenes" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_scene_actions"("id", "scene_id", "device_type", "device_id", "command", "params", "delay_ms", "sort_order", "enabled", "created_at", "updated_at") SELECT "id", "scene_id", "device_type", "device_id", "command", "params", "delay_ms", "sort_order", "enabled", "created_at", "updated_at" FROM "scene_actions"`);
        await queryRunner.query(`DROP TABLE "scene_actions"`);
        await queryRunner.query(`ALTER TABLE "temporary_scene_actions" RENAME TO "scene_actions"`);
        await queryRunner.query(`CREATE INDEX "IDX_046439be52ebc0d499e7e16ca5" ON "scene_actions" ("scene_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_046439be52ebc0d499e7e16ca5"`);
        await queryRunner.query(`ALTER TABLE "scene_actions" RENAME TO "temporary_scene_actions"`);
        await queryRunner.query(`CREATE TABLE "scene_actions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scene_id" integer NOT NULL, "device_type" varchar(32) NOT NULL, "device_id" varchar(128) NOT NULL, "command" varchar(64) NOT NULL, "params" text NOT NULL DEFAULT ('{}'), "delay_ms" integer NOT NULL DEFAULT (0), "sort_order" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "scene_actions"("id", "scene_id", "device_type", "device_id", "command", "params", "delay_ms", "sort_order", "enabled", "created_at", "updated_at") SELECT "id", "scene_id", "device_type", "device_id", "command", "params", "delay_ms", "sort_order", "enabled", "created_at", "updated_at" FROM "temporary_scene_actions"`);
        await queryRunner.query(`DROP TABLE "temporary_scene_actions"`);
        await queryRunner.query(`CREATE INDEX "IDX_046439be52ebc0d499e7e16ca5" ON "scene_actions" ("scene_id") `);
        await queryRunner.query(`DROP TABLE "admin_auth_v1"`);
        await queryRunner.query(`DROP INDEX "IDX_9a56f667c22a7afc04b8a45f83"`);
        await queryRunner.query(`DROP INDEX "IDX_b63189bf8e5abf5b9188acca96"`);
        await queryRunner.query(`DROP INDEX "IDX_da59bc445b71f4e501ce8bb05b"`);
        await queryRunner.query(`DROP INDEX "IDX_b5262085cf88e336618af2cc68"`);
        await queryRunner.query(`DROP INDEX "IDX_5ad88d0fa69fb016405bc8ddd8"`);
        await queryRunner.query(`DROP TABLE "alerts"`);
        await queryRunner.query(`DROP INDEX "IDX_a54ecddcea1bb90f7cf90ccb1f"`);
        await queryRunner.query(`DROP TABLE "app_release_v1"`);
        await queryRunner.query(`DROP TABLE "audio_desired_link"`);
        await queryRunner.query(`DROP INDEX "IDX_aabbc290e3165fe043d1ad565d"`);
        await queryRunner.query(`DROP TABLE "audio_input_source"`);
        await queryRunner.query(`DROP INDEX "IDX_b76f6076f7da68d767258ac71b"`);
        await queryRunner.query(`DROP TABLE "audio_output_zone"`);
        await queryRunner.query(`DROP INDEX "IDX_de2c659baf331df3651dad07e5"`);
        await queryRunner.query(`DROP TABLE "audio_scene"`);
        await queryRunner.query(`DROP INDEX "IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "IDX_f23279fad63453147a8efb46cf"`);
        await queryRunner.query(`DROP INDEX "IDX_01993ae76b293d3b866cc3a125"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_96db6bbbaa6f23cad26871339b"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "client_auth_v1"`);
        await queryRunner.query(`DROP INDEX "IDX_c37da3607f7214c3dda1803d09"`);
        await queryRunner.query(`DROP INDEX "IDX_1f102b281aa9b07d72ca5197ed"`);
        await queryRunner.query(`DROP INDEX "IDX_25a895dfc7796eab1da289796f"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP INDEX "IDX_16f484a7424fc3685085c8a688"`);
        await queryRunner.query(`DROP INDEX "IDX_6bc70405ac48a8c43c7d4f953e"`);
        await queryRunner.query(`DROP TABLE "driver_templates"`);
        await queryRunner.query(`DROP INDEX "IDX_647fdcd283a2d28954f35e8159"`);
        await queryRunner.query(`DROP INDEX "IDX_85258d496323a08d27df01816f"`);
        await queryRunner.query(`DROP INDEX "IDX_fbb2a88e4560cf92580a40614b"`);
        await queryRunner.query(`DROP TABLE "hardware_units"`);
        await queryRunner.query(`DROP INDEX "IDX_3f4da5a85603142e0b7e34b6c0"`);
        await queryRunner.query(`DROP INDEX "IDX_d818582834958bb3838ea32be5"`);
        await queryRunner.query(`DROP TABLE "hvac_indoor"`);
        await queryRunner.query(`DROP INDEX "IDX_57a6442697b26d72122d1602c2"`);
        await queryRunner.query(`DROP TABLE "hvac_zone"`);
        await queryRunner.query(`DROP INDEX "IDX_e9f27da6e6305bfcf52c859807"`);
        await queryRunner.query(`DROP INDEX "IDX_0890fb46621b4af51ca658c591"`);
        await queryRunner.query(`DROP TABLE "light_group"`);
        await queryRunner.query(`DROP INDEX "IDX_3dec5d43d95019fa40b4c0f615"`);
        await queryRunner.query(`DROP TABLE "light_zone"`);
        await queryRunner.query(`DROP INDEX "IDX_7b5020667b8938c708210d09a6"`);
        await queryRunner.query(`DROP TABLE "media_assets"`);
        await queryRunner.query(`DROP INDEX "IDX_4b5947763b1f5e3e33942ab5b7"`);
        await queryRunner.query(`DROP INDEX "IDX_05aa79d806bd30b09b756dce93"`);
        await queryRunner.query(`DROP INDEX "IDX_a6e545189a34b54117d9fc7f0e"`);
        await queryRunner.query(`DROP INDEX "IDX_c1fd6d1b5856cc0958b2add833"`);
        await queryRunner.query(`DROP TABLE "operation_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_7c5faf5c86c501f67d8533d0b1"`);
        await queryRunner.query(`DROP TABLE "playback_channels"`);
        await queryRunner.query(`DROP INDEX "IDX_83aea8276a638b5680b2256b41"`);
        await queryRunner.query(`DROP TABLE "playback_history"`);
        await queryRunner.query(`DROP INDEX "IDX_0bd653b06977753eb94f5ee893"`);
        await queryRunner.query(`DROP TABLE "playlist_item"`);
        await queryRunner.query(`DROP INDEX "IDX_d0389afb4f67214ffd193d4a8a"`);
        await queryRunner.query(`DROP TABLE "power_circuit"`);
        await queryRunner.query(`DROP INDEX "IDX_b10a37bb435779760fd8d65c85"`);
        await queryRunner.query(`DROP INDEX "IDX_096dc7077ab41db07ff421f849"`);
        await queryRunner.query(`DROP INDEX "IDX_dfd7d6c80251c65d25d66a0103"`);
        await queryRunner.query(`DROP INDEX "IDX_796db607efd396a74b80a9c931"`);
        await queryRunner.query(`DROP INDEX "IDX_d034c032080709f018caf9e0f3"`);
        await queryRunner.query(`DROP TABLE "scene_executions"`);
        await queryRunner.query(`DROP INDEX "IDX_f376f84e976d24c79aadbf4b58"`);
        await queryRunner.query(`DROP TABLE "scenes"`);
        await queryRunner.query(`DROP INDEX "IDX_046439be52ebc0d499e7e16ca5"`);
        await queryRunner.query(`DROP TABLE "scene_actions"`);
        await queryRunner.query(`DROP TABLE "system_branding_v2"`);
        await queryRunner.query(`DROP INDEX "IDX_1dae30dc36edfd45fbe40a3ff8"`);
        await queryRunner.query(`DROP INDEX "IDX_7fb5dafd650ee26023627ce351"`);
        await queryRunner.query(`DROP TABLE "scheduler_tasks"`);
        await queryRunner.query(`DROP INDEX "IDX_47f725cebdba28aa831919e35b"`);
        await queryRunner.query(`DROP INDEX "IDX_e17e3fceab179e221cfbf12702"`);
        await queryRunner.query(`DROP INDEX "IDX_8aa4cd9b5b3df766131a6cf6f1"`);
        await queryRunner.query(`DROP INDEX "IDX_4d6364e37ab492de1890459ce9"`);
        await queryRunner.query(`DROP INDEX "IDX_8421ec201cd5faa739bea5ae69"`);
        await queryRunner.query(`DROP TABLE "test_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_f5aec40c90481934f34812a27b"`);
        await queryRunner.query(`DROP INDEX "IDX_2c22473aebe935929206fa0859"`);
        await queryRunner.query(`DROP INDEX "IDX_a9dfa2b01ea47f870d816a40a1"`);
        await queryRunner.query(`DROP TABLE "uat_records"`);
        await queryRunner.query(`DROP INDEX "IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
